# Generated by Django 3.2.6 on 2021-08-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Photo_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Oneline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
